### ISSUE TITLE
请问数学公式是怎么编写的？

### ISSUE THREAD

**Issue by JinsYin** [ShawnZhong/shawnzhong.github.io#1]
hi,shawnzhong，我想了解一下你网站 http://shawnzhong.com/category/mathematics/linear-algebra/ 中的行列式、矩阵等数学公式是怎么编写的，word?

**Comment by ShawnZhong** [comment]
记笔记用的 OneNote，公式编辑器是 Office 自带的那一套。

**Comment by JinsYin** [comment]
thanks，不过想要在 GitHub 中进行托管的话有些不方便，GitHub 的 markdown 又不支持 latex。

**Comment by ShawnZhong** [comment]
可以用 Jupyter Notebook，像 https://github.com/zlotus/notes-linear-algebra

**Comment by JinsYin** [comment]
简单看了下，感觉很行。不过我很难改变 markdown 的写作方式，而且需要同时兼容 GitHub 和 GitBook。
